# Header
menu:
  首页: /
  #about: /about
  所有文章: /archives
  #commonweal: /404.html
  #随笔: /tags/随笔
  

# SubNav
subnav:
  github: https://github.com/sostudy/sostudy.github.io
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  twitter: https://twitter.com/Soyl_liu
  #google: "#"
  facebook: https://www.facebook.com/profile.php?id=100006370873023
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

#搜索功能 
swift_search:
 enable: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: http://7xt9fi.com1.z0.glb.clouddn.com/head_portrait_small.png
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
#  托蒂的博客: http://localhost:4000/

#开启目录功能
#toc: true

#百度统计
baidu_tongji: true

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 倩倩，今天的月色真美！！